server:
  port: 8084

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/payment_db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:admin123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true

app:
  sepay:
    api-key: ${SEPAY_API_KEY:2WJ8QVZG2XB1LH4KD03BPQWYPD4KUFOHIBMNA97YE1TRF5RINSLESUWZCGLXCGLN}
    bank-account: ${SEPAY_BANK_ACC:2511112005}
    bank-code: ${SEPAY_BANK_CODE:MBBank}
    account-holder: ${SEPAY_ACC_HOLDER:Ngô Giản Tuy}
    qr-base: ${SEPAY_QR_BASE:https://qr.sepay.vn/img}
    qr-template: ${SEPAY_QR_TEMPLATE:compact}
    expires-minutes: ${SEPAY_EXPIRES_MIN:15}
  kafka:
    topics:
      payment-completed: payment.completed
      payment-failed:    payment.failed
  outbox:
    poll-interval-ms: 2000
    batch-size: 50

management:
  endpoints:
    web:
      exposure:
        include: health, info, flyway, prometheus, metrics
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    enabled: ${TRACING_ENABLED:false}        # bật = true khi đã chạy Zipkin (Docker)
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
